python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST01.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST04.BIN OUTDAT

python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST05.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST06.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST07.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST08.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST09.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0A.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0B.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0C.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0D.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0D01.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0E.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0E01.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0E02.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0F.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST10.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST11.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST12.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST13.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1301.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST14.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST15.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST16.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST17.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1703.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST18.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1802.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST19.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1902.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1A.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1A01.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1B.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1B01.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1D.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1E.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1F.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1F01.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1F02.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST20.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST21.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST22.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST23.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST24.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST25.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2502.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST26.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2601.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST27.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2701.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST28.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST29.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2901.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2A.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2B.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2C.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2D.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2E.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2F.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST30.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3001.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST31.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST32.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST33.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST34.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST35.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3501.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3502.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST36.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST37.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST38.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST39.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3901.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3B.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3C.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3C01.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3D.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3E.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3F.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST40.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST41.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST42.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST43.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST44.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST45.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST47.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST48.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST4A.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST4B.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST4C.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST4D.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST4E.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST4F.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST50.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST51.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST52.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST55.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST56.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST58.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST59.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST5A.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST5B.BIN OUTDAT

python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST04T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST18T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1802T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1804T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST55T.BIN OUTDAT

python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST00T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0AT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST0CT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1AT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1A01T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1B01T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1BT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST1FT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST2CT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3001T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST30T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3BT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST3FT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST47T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST57T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST59T.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST5AT.BIN OUTDAT
python ..\Tools\combbin.py -x ..\USRDIR\DAT\ST5BT.BIN OUTDAT

python ..\Tools\combbin.py -x ..\USRDIR\COMMON\GAME.BIN OUTCOMMON
python ..\Tools\combbin.py -x ..\USRDIR\COMMON\SUBSCN.BIN OUTCOMMON
python ..\Tools\combbin.py -x ..\USRDIR\COMMON\TITLE.BIN OUTCOMMON
pause